#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dn=${thisdir##*/}
#vernum=$(hg id -r '::. and tag()' | tr " " "\n" | sed -n 2p)
arname=$thisdir/../$dn.tar.gz
if [ -e $arname ]
then
  rm $arname
fi
tar -zcvf $arname -C $thisdir/../ $dn/databrowse $dn/databrowse_wsgi $dn/setup.py $dn/README $dn/COPYING $dn/MANIFEST.in
